export const RUNTIME_ENVIRONMENT_HANDLER_CHANNELS = [
  'runtimeEnvironments:list',
  'runtimeEnvironments:addFromPairingCode',
  'runtimeEnvironments:verifyAndAddFromPairingCode',
  'runtimeEnvironments:resolve',
  'runtimeEnvironments:remove',
  'runtimeEnvironments:disconnect',
  'runtimeEnvironments:connect',
  'runtimeEnvironments:retryControlConnection',
  'runtimeEnvironments:prepareBrowserClientHostPlacement',
  'runtimeEnvironments:getStatus',
  'runtimeEnvironments:call',
  'runtimeEnvironments:subscribe',
  'runtimeEnvironments:unsubscribe',
  'runtimeEnvironments:listPendingOrcadMigrations',
  'runtimeEnvironments:preflightOrcadTarget',
  'runtimeEnvironments:deployOrcad',
  'runtimeEnvironments:updateOrcad',
  'runtimeEnvironments:getOrcadStatus',
  'runtimeEnvironments:rollbackOrcad',
  'runtimeEnvironments:recoverOrcad',
  'runtimeEnvironments:stopOrcad'
] as const
